### ISSUE TITLE
Error Unsupported fieldtype: T

### ISSUE THREAD

**Issue by dkeza** [SebastiaanKlippert/go-foxpro-dbf#2]
When I try to read field of type DATETIME. i get this error:

Error Unsupported fieldtype: T

Gist:
https://gist.github.com/dkeza/11c5dccc639a4ba7332188c6460e5350

Is DATETIME field supported?

**Comment by SebastiaanKlippert** [comment]
It looks like it is not supported. As stated in the readme I have only tested this package with a Xbase application, they only have a subset of field types that are supported.
I now only support M, C, I, B, D, L, V, N and F fields.
But I could build in the other types if needed. I will play around with a new FoxPro DBF so my package can handle more types of DBF files..
Could you include the DBF created by the code in your gist or perhaps even include some more field types like Y (Currency), G (General) and P (picture). Than I have my own data and your data to test against.

Thanks.

**Comment by SebastiaanKlippert** [comment]
I have added support for more FoxPro fields, see the updated README for which types are supported now.

If you need more, open an issue 😄

**Comment by SebastiaanKlippert** [comment]
Also: If you would like to test the DateTime type I would be happy.

I am not sure my implementation is 100% correct, the timestamp is stored as a Julian date and timestamp and I am not sure the Julian implementation is correct. I have never used this format so I have used another Go package for this.
On some files I get years like -4953 but I am not sure if this is because the date is empty or something buggy is happening.

**Comment by dkeza** [comment]
I have tested currency and datetime fields.
Currency field is now correctly converted.
But with datetime field i get strange behavior:

DBF: 
PA_ADRMUPD = 14.11.2016 09:00:16

GO: 
pa_adrmupd, _ := record2.Field(param2.FieldPos("PA_ADRMUPD"))
log.Println(pa_adrmupd)
//2016-11-14 00:00:01.880817088 +0000 UTC

**Comment by dkeza** [comment]
I changed gist, and added testf.dbf for testing:

https://gist.github.com/dkeza/347a50555c45220286dfcd5f77499773

Just download attached jpg file, and rename it to testf.dbf, Github doesn't allow DBF files to be attached.

**Comment by SebastiaanKlippert** [comment]
Thanks for testing! I will take another look today.
Looks like the time part in your DBF is stored differently as in the DBF I found online.

**Comment by SebastiaanKlippert** [comment]
I have just added your DBF to my tests and everything seems to pass...

I see DTIME field with value "14-11-2016 09:10:44" in my editor.
![dk](https://cloud.githubusercontent.com/assets/6223360/20260519/475dfa82-aa5a-11e6-959f-b5fbe8c00a56.png)

This is also what I get in my test, both on my Windows and machine and Travis CI on Linux:
`reader_test.go:483: DTIME: 2016-11-14 09:10:44 +0000 UTC`

If I run your gist code I get:
```
2016/11/14 11:11:37 2016-11-14 09:10:44 +0000 UTC <nil>
2016/11/14 11:11:37 8027846523 <nil>
2016/11/14 11:11:37 1234567890.123400
```
This all seems OK to me... so I am not sure what you are seeing.... did you pull the latest version?

**Comment by dkeza** [comment]
Yes, i have pulled latest version.
This is weird. When i run my gist code, i get:

```
2016/11/14 11:38:49 2016-11-13 23:59:58.521624576 +0000 UTC <nil>
2016/11/14 11:38:49 8027846523 <nil>
2016/11/14 11:38:49 1234567890.123400
```

Maybe it is some Windows OS regional setting issue. I would try it on another PC.

**Comment by dkeza** [comment]
Strange, on another PC (in VirtualBox) I get same wrong datetime. Maybe it has something to do with using 32bit version of Go?

**Comment by SebastiaanKlippert** [comment]
I am guessing it has something to do with time zone info which is missing. Which tot time zone are you using on these PCs and which OS? Do you have Go installed or are you just running the executable? 
I will test some more later today if I have time.

**Comment by SebastiaanKlippert** [comment]
Hi again,

Are you running on a 32 bit architecture or OS?
Because that would explain the error, was having some trouble figuring this out but it became obvious when I tried to dissect the code and have a look at the numbers I was getting.
The previous implementation used the whole millisecond time since midnight as nanosecond value in time.Date which would result in a value > int32. Should have seen than before 😊 

I have have now split the calculation to use seconds and the remainder as nanoseconds which should keep the millisecond resolution, although my DB editor does not support setting anything less significant than seconds.

I you could please try again if this now also works for you I would really appreciate it 👍

**Comment by dkeza** [comment]
Hey, I can confirm, it is working now!

Thank You

**Comment by SebastiaanKlippert** [comment]
Great!
