### ISSUE TITLE
Overriding ValidFileVersionFunc

### ISSUE THREAD

**Issue by chrisalcantara** [SebastiaanKlippert/go-foxpro-dbf#8]
Getting this error: `Error: untested DBF file version: 3 (3 hex), try overriding ValidFileVersionFunc to open this file anyway` 

When opening a large DBF. I still want to open it regardless, but I don't know how to "override ValidFileVersionFunc" to do it anyway. 

Any help?

**Comment by SebastiaanKlippert** [comment]
It is there because I don't want to be responsible.

See test `TestOpeningUntestedFile`, but I will add a sample to GoDoc, that mayt be easier for most people to understand.

You have to specify the file version flag which is accepted and return no error then. In your case (03) it could be something like:
```go
	dbf.ValidFileVersionFunc = func(version byte) error {
		if version == 0x03 {
			return nil
		}
		return errors.New("not 0x03")
	}
```

Do this in your own code, and before opening the file and then you will be fine.

**Comment by SebastiaanKlippert** [comment]
Added function [SetValidFileVersionFunc](https://godoc.org/github.com/SebastiaanKlippert/go-foxpro-dbf#SetValidFileVersionFunc) with an example.
